### ISSUE TITLE
find out how ICA is related to FA

### ISSUE THREAD

**Issue by davidwhogg** [rossfadely/consomme#2]

**Comment by rossfadely** [comment]
I believe I understand, and think we may actually want ICA.  Folks are going to want to interpret the lambdas, which is not really possible for FA due to rotational degeneracies.

**Comment by davidwhogg** [comment]
If that's the only difference, then there is no difference, but I think the differences are bigger; ICA is more general, no?

**Comment by rossfadely** [comment]
Check this http://arxiv.org/pdf/1301.5930v1.pdf

**Comment by davidwhogg** [comment]
I don't see how their method is ICA.  It is a FA with a regularization that requires orthogonality or non-negativity of the factors.  But there is no "I" in it.  No?

**Comment by rossfadely** [comment]
Agreed.  I posted the paper without looking at the model, and indeed it does not yield independent solutions.  In fact, the author's even say so... not sure how ICA is appropriate terminology.  Nevertheless, they are pretty close to the FA version of foam.

**Comment by davidwhogg** [comment]
good, you just earned beer.  (I blogged the request for an astronomical use of FA.)

**Comment by rossfadely** [comment]
woo-hoo!
