### ISSUE TITLE
change "sample mean" in plots to "true mean"

### ISSUE THREAD

**Issue by davidwhogg** [rossfadely/consomme#7]
I think when we have fake data and we show the real answer, we should call it the "truth".

Can you also propagate this change through the full text?

**Comment by rossfadely** [comment]
Well, actually there are two "truth"s.  There is what I am calling the "true mean" which is the mean of the distribution from which the sample is drawn, i.e., what you would get if you had infinite samples.  There is also what I am calling the "sample mean" which is the mean one would get for a finite size sample, under the presence of no noise.  The two have important distinctions.

**Comment by davidwhogg** [comment]
Understood.  Then I suggest "true sample mean"  Just to make clear that it is not what is traditionally meant by "sample mean" which would be the empirical average of the data

**Comment by rossfadely** [comment]
Done.
