### ISSUE TITLE
IVW PCA vs HMF

### ISSUE THREAD

**Issue by davidwhogg** [rossfadely/consomme#9]
can you cite HMF (Tsalmantza and Hogg) and compare it to IVW PCA (the Bailey method) at least in words.  I don't need HMF to be part of this paper, but I want to see it compared.

**Comment by rossfadely** [comment]
Hmm, looking at the papers you are both optimizing the same objective (chi^2, not just squared residuals).  It seems like you just have different ways of defining the bases and finding the optimum.

Is there a place where the HMF code lives?  It would be nice to run it on some of the toys we have.

**Comment by davidwhogg** [comment]
Does Bailey make this comparison?

The code is here, in useless form:

https://github.com/davidwhogg/SpectralArchetypes

**Comment by rossfadely** [comment]
The two methods are the same, just different code.
